avalia_pares/apps/atividades/urls.py
from django.conf.urls import patterns, url


from avalia_pares.apps.atividades.views import *
from avalia_pares.apps.professor.views import baixa_atividade

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'avaliacao_pares.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^treplicar/(?P<slug>[a-zA-Z0-9-]+)$', posta_treplica,name='aluno_treplica'),
    url(r'^replica/(?P<slug>[a-zA-Z0-9-]+)$', posta_replica,name='aluno_replica'),
    url(r'^comenta/(?P<slug>[a-zA-Z0-9-]+)$', posta_comentario,name='aluno_comentario'),
    url(r'^posta/nota/(?P<slug>[a-zA-Z0-9-]+)$', posta_notas,name='aluno_posta_nota'),
    url(r'^posta/nota_avaliador/(?P<slug>[a-zA-Z0-9-]+)$', posta_nota_avaliador,name='aluno_posta_nota_avaliador'),

    url(r'^detalhes/(?P<slug>[a-zA-Z0-9-]+)$', detalhe_atividade,name='detalhe_atividade'),
    url(r'^download/(?P<slug>[a-zA-Z0-9-]+)$', baixa_atividade,name='baixa_atividade'),
    url(r'^notas/(?P<slug_atividade>[a-zA-Z0-9-]+)$',getNotasAluno,name='notas_individuais_detalhadas'),

    


)

avalia_pares/apps/professor/urls.py
from django.conf.urls import patterns, url

from avalia_pares.apps.professor.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'avaliacao_pares.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),


#professor
    url(r'^home$',home_professor ,name='home_professor'),
    url(r'^disciplinas$', disc_professor,name='professor_disciplinas'),
    url(r'^disciplina/(?P<slug>[a-zA-Z0-9-]+)$', disc_professor_detail,name='professor_disciplinas_detail'),#Ver detalhes da disciplina
    url(r'^disciplina/pendente/(?P<slug>[a-zA-Z0-9-]+)$', disc_aluno_pendente,name='disc_aluno_pend'),#Retorna e deixa gerenciar alunos pendentes
    url(r'^disciplina/solicitou/(?P<slug>[a-zA-Z0-9-]+)$', aceitar_negar_aluno,name='aceitar_negar_aluno'),#Retorna e deixa gerenciar alunos pendentes
    url(r'^disciplina/matriculado/(?P<slug>[a-zA-Z0-9-]+)$', disc_aluno_mat,name='disc_aluno_mat'),
    url(r'^criar/disciplina',cria_Disciplina,name='professor_cria_disciplina'),
    url(r'^criar/atividade/(?P<slug>[a-zA-Z0-9-]+)$',cria_atividade,name='professor_cria_atividade'),#Cria uma atividade relacionado a uma disciplina
    url(r'^atualizar_dados',atualiza_perfil_professor,name='atualiza_dados_professor'),#atualizar os dados
    url(r'^editar/disciplina/(?P<slug>[a-zA-Z0-9-]+)$',Edita_Disciplina,name='Edita_Disciplina'),
    url(r'^editar/atividade/(?P<slug>[a-zA-Z0-9-]+)$',Edita_Atividade,name='Edita_Atividade'),
    url(r'^atividades$',Lista_Atividades,name='Lista_Atividades'),
    url(r'^atividades/excluir/(?P<slug>[a-zA-Z0-9-]+)$', excluir_atividade,name='excluir_atividade'),
    url(r'^atividades/notas/(?P<slug_atividade>[a-zA-Z0-9-]+)$', nota_atividade_alunos,name='nota_atividade'),

    url(r'^alocar/(?P<slug>[a-zA-Z0-9-]+)$',alocar_trabalhos,name='alocar_trabalhos')#Aloca os trabalhos caso seja chamada

)

avalia_pares/urls.py
__author__ = 'allan'

from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'avaliacao_pares.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^aluno/', include('avalia_pares.apps.aluno.urls')),
    url(r'^professor/', include('avalia_pares.apps.professor.urls')),
    url(r'^disciplina/', include('avalia_pares.apps.disciplina.urls')),
    url(r'^atividade/', include('avalia_pares.apps.atividades.urls')),

)

avaliacao_pares/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'avaliacao_pares.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('core.apps.config.urls')),
    url(r'^av_pares/',include('avalia_pares.urls')),
    url(r'^usuarios/', include('core.apps.autenticar.urls')),
)

avalia_pares/apps/atividades/models.py
# -*- coding: utf-8 -*-

import hashlib
import os
import random

from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import transaction
from django.db.models.signals import pre_save, post_save, pre_delete
from django.dispatch.dispatcher import receiver
from django.utils import timezone
from django.db.models import Sum
from avalia_pares.apps.atividades.utils import media, mediana, conv_date_data, conv_date_horas
from avalia_pares.apps.atividades.validators import valida_nota, valida_peso
from core.apps.ava.models import Aluno, Atividades
from django.db import models








#Modelo de atividades
class AtividadesPeer(models.Model):
    atividade=models.ForeignKey(Atividades)
    fase_Inicio=models.DateTimeField(verbose_name="Data De Inicio da atividade")
    fase_submeter=models.DateTimeField(verbose_name="Data limite para submissão")
    fase_comentar=models.DateTimeField(verbose_name="Inicio do comentário")
    fase_replica=models.DateTimeField(verbose_name="Inicio da Réplica")
    fase_treplica=models.DateTimeField(verbose_name="Inicio da tréplica")
    fase_nota=models.DateTimeField(verbose_name="Inicio da postagem de notas")
    fase_finalizada=models.DateTimeField(verbose_name="Data Final da atividade")
    def __unicode__(self):

        return self.titulo
    def get_absolute_url(self):

        return reverse(viewname='aluno_vis_atividade',kwargs={'slug':self.slug,'slug_disc':self.disciplina.slug})

    def get_submeter_url(self):

        return reverse(viewname='aluno_sub_atividade',kwargs={'slug':self.slug,'slug_disc':self.disciplina.slug})


    #Aloca as respostas, ou seja, cria um espaço para que possa haver comentario, replica e treplica de uma atividade
    @transaction.atomic
    def aloca_atividades(self,atividadesSubmetidas=False):

        #Determina o intervalo de indices para quantidade de avaliadores par
        if self.disciplina.quantidade_de_avaliadores%2==0:
            nr_avaliadores=self.disciplina.quantidade_de_avaliadores/2-1
            min=-1*(nr_avaliadores)-1
            print "par",nr_avaliadores,min

        #Determina o intervalo de indice para quantidade de avalaliadores impares
        else:
            nr_avaliadores=self.disciplina.quantidade_de_avaliadores/2
            min=-1*(nr_avaliadores)

        index=0

        if not atividadesSubmetidas:
            atividadesSubmetidas=AtividadeSubmetidas.objects.filter(atividade=self).order_by('?')
        #Valor negativo, a esquerda do base para pegar os avaliadores

        for atvd in atividadesSubmetidas:


            for pos in range(min,nr_avaliadores+1):
                print pos
                avaliador=atividadesSubmetidas[(index-pos)%len(atividadesSubmetidas)].aluno
                resposta=Resposta()
                resposta.atividade=atvd
                resposta.avaliador=avaliador

                resposta.save()


            index+=1
        self.aloca_nota_atividades()

    #Relaciona notas as respostas de acordo com os criterios da atividade
    @transaction.atomic
    def aloca_nota_atividades(self):
        resposta=Resposta.objects.filter(atividade__atividade=self)
        criterio=Criterio.objects.filter(atividade=self)
        for resp in resposta:

            for crit in criterio:
                nota=Notas(resposta=resp,criterio=crit)
                nota.save()





#Modelo para comportar as atividades submetidas
class AtividadeSubmetidas(models.Model):
    nota_final_media=models.FloatField(blank=True,null=True,validators=[valida_nota],max_length=5,default=0)
    nota_final_mediana=models.FloatField(blank=True,null=True,validators=[valida_nota],max_length=5,default=0)
    arquivo=models.FileField(upload_to='atividades/arquivos/atividades/submetidas')
    aluno=models.ForeignKey(Aluno)
    atividade=models.ForeignKey(Atividades)
    data_submissao=models.DateTimeField(auto_now=True,editable=False)
    slug=models.SlugField(max_length=40,db_index=True,blank=True,unique=True)
    class Meta:
        unique_together=('aluno','atividade')
    def __unicode__(self):
        return self.aluno.nome

    #Calcula a nota total do estudante
    @transaction.atomic
    def nota_total(self,forcar=False):
        total=[]
        respostas=Resposta.objects.filter(atividade=self)
        for resp in respostas:

            total.append(resp.nota_total)

        penitencia=self.calc_penalidade()
        #Aplicando a penitencia na media
        med=media(total)
        med=med-(med*penitencia)/100.0

        #Aplicando a penitencia na mediana
        median=mediana(total)
        median=median-(median*penitencia)/100.0
        self.nota_final_media=med

        self.nota_final_mediana=median

        self.save()
        return self.nota_final_mediana

    #calcula a penalidade com base na penalidade definida na disciplina da atividade
    def calc_penalidade(self):
        penalidade=self.atividade.disciplina.penalidade
        resp=Resposta.objects.filter(avaliador=self.aluno,atividade__atividade=self.atividade)
        resp2=Resposta.objects.filter(atividade__atividade=self.atividade,atividade__aluno=self.aluno)
        tot=0
        for r in resp:
            if r.comentario == None:
                tot+=1
            if r.treplica == None:
                tot+=1

        for r in resp2:
            if r.replica==None:
                tot+=1
        penalidade*=tot

        if penalidade>100:
            penalidade=100

        return penalidade
    #Submissão entre as datas corretas
    def submeter(self):

        if self.atividade.fase_Inicio >= timezone.now():
            return "Só será permito submissão a partir de: %s de %s"%(conv_date_horas(self.atividade.fase_Inicio),conv_date_data(self.atividade.fase_Inicio))
        elif timezone.now() <=self.atividade.fase_submeter:
            self.save()
            return "Enviado com sucesso"

        else:
            return "O tempo para submeter expirou na hora: %s de %s"%(conv_date_horas(self.atividade.fase_submeter),conv_date_data(self.atividade.fase_submeter))

#modelo de notas, onde é referenciado uma resposta, pelo motivo de ter uma nota pra cada criterio relacionado com uma correção
class Notas(models.Model):
    nota=models.FloatField(blank=True,validators=[valida_nota],null=True,default=0)
    resposta=models.ForeignKey('Resposta')
    criterio=models.ForeignKey('Criterio')
    data_post=models.DateTimeField(auto_now_add=True,editable=False)
    def __unicode__(self):
        return "Atividade: %s avaliador: %s avaliado: %s"%(self.criterio.atividade,self.resposta.avaliador,self.resposta.atividade.aluno)

    def inserir_nota(self,aluno):
        if self.resposta.avaliador == aluno:
            atividade=self.resposta.atividade.atividade
            data_hoje=timezone.now()
            if atividade.fase_treplica <= data_hoje <= atividade.fase_nota:
                self.save()
                return "nota inserida com sucesso"

        raise Exception("ainda não é dia para postagem de notas!")




#Criterios estão relacionados com atividades, o administrador pode cadastrar n criterios.
class Criterio(models.Model):
    peso=models.PositiveSmallIntegerField(validators=[valida_peso])
    descricao=models.TextField(max_length=250)
    atividade=models.ForeignKey(Atividades)

    def __unicode__(self):
        return "criterio: %s  | peso =%s   | atividade =%s"%(self.descricao,self.peso,self.atividade)
    #Função para insersão de critério com cuidado para não inserir onde não é possível
    def inserir_criterio(self):
        max=100 #somatorio do peso maximo
        atual=0
        self.atividade.criterio_set.aggregate(Sum('peso'))
        criterios=Criterio.objects.filter(atividade=self.atividade)
        for crit in criterios:
            atual+=crit.peso
        #verifica se a soma dos pesos de todos os criterios é menor ou igual a 100
        if self.peso <= max-atual and atual <=max:
            self.save()
            return "Criterio inserido com sucesso"
        else:
            return "Criterio está com peso maior do que o possivel - a soma de todos os critérios deve ser igual a 100"


# class Fase(models.Model):
#     SUBMISSAO='sub'
#     POST_COMENT='p_coment'
#     POST_NOTA='p_nota'
#     CHOICES=((SUBMISSAO,"Submissão"),(POST_COMENT,'Comentários'),(POST_NOTA,"Postar Notas"))
#
#     tipo=models.CharField(choices=CHOICES,max_length=15)
#     data_inicio=models.DateTimeField()
#     data_fim=models.DateTimeField()
#     descricao=models.TextField(max_length=150)
#     atividade=models.ForeignKey(Atividades,related_name="Atividade_Fase")
#     def __unicode__(self):
#         return self.descricao

#Toda atividade submetida terá o numero de respostas igual ao de avaliadores.
class Resposta(models.Model):
    nota_total=models.FloatField(default=0,verbose_name="Nota total do aluno avaliado",blank=True,max_length=2,null=True,validators=[valida_nota])
    nota_para_avaliador=models.FloatField(default=0,blank=True,null=True,max_length=2,validators=[valida_nota])
    avaliador=models.ForeignKey(Aluno,related_name='Avaliador')
    atividade=models.ForeignKey(AtividadeSubmetidas,related_name="Atividade Submetida")
    comentario=models.CharField(max_length=200,blank=True,null=True)
    replica=models.CharField(max_length=200,blank=True,null=True)
    treplica=models.CharField(max_length=200,blank=True,null=True)
    slug=models.SlugField(max_length=40,db_index=True,blank=True,null=True,unique=True)

    class Meta:
        unique_together=('avaliador','atividade',)

    def __unicode__(self):
        return "Avaliador=%s [Avaliado: %s]"%(self.avaliador,self.atividade.aluno)
    #Calcula a nota da resposta, baseado em cada nota/critério
    @transaction.atomic
    def calcula_nota(self,forcar=False):

        self.nota_total=0
        notas = self.notas_set.all()

        for nota in notas:

            self.nota_total+=(nota.nota * nota.criterio.peso)/100.0

        self.save()

avalia_pares/apps/professor/forms.py
from django import forms

avalia_pares/apps/atividades/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.core import serializers
from django.db import transaction
from avalia_pares.apps.atividades.models import AtividadesPeer, Resposta, Notas
from core.apps.ava.decorators import is_professor, is_aluno


@login_required
@is_professor()
def detalhe_atividade(request,slug):
    atividade=AtividadesPeer.objects.get(atividade__slug=slug)
    return render(request, 'detalhe_atividade.html',{'atividade':atividade})


@login_required
@is_aluno()
def posta_comentario(request,slug):
    if request.method == 'POST':
        aluno=request.user.aluno
        resposta=Resposta.objects.get(slug=slug)
        comentario=request.POST['comentario']
        msg=resposta.posta_comentario(comentario=comentario,aluno=aluno)

        return redirect(reverse(viewname='aluno_comentarioEnotas',kwargs={'slug':slug}))
    return HttpResponseRedirect("/home")


@login_required
@is_aluno()
def posta_replica(request,slug):

    if request.method == 'POST':
        aluno=request.user.aluno
        resposta=Resposta.objects.get(slug=slug)
        replica=request.POST['replica']
        msg=resposta.posta_replica(replica=replica,aluno=aluno)

        return redirect(reverse(viewname='aluno_comentarioEnotas',kwargs={'slug':slug}))
    return HttpResponseRedirect("/home")

@login_required
@is_aluno()
def posta_treplica(request,slug):

    if request.method == 'POST':
        aluno=request.user.aluno
        resposta=Resposta.objects.get(slug=slug)

        treplica=request.POST['treplica']

        msg = resposta.posta_treplica(treplica=treplica,aluno=aluno)

        return redirect(reverse(viewname='aluno_comentarioEnotas',kwargs={'slug':slug}))

    return HttpResponseRedirect("/home")

@login_required
@is_aluno()
@transaction.atomic
def posta_notas(request,slug):
    if request.method=='POST':
        #notas=request.POST.get('nota')
        #criterios=request.POST.get('criterio')

        notas=request.POST.getlist('nota')
        criterios=request.POST.getlist('criterio')
        for cont in range(0,len(notas)):

            nota=Notas.objects.get(criterio=criterios[cont],resposta__slug=slug)

            nota.nota=notas[cont].replace(",",".")
            nota.inserir_nota(request.user.aluno)

        return redirect(reverse(viewname='aluno_comentarioEnotas',kwargs={'slug':slug}))
    return HttpResponseRedirect("/home")

@login_required
@is_aluno()
def posta_nota_avaliador(request,slug):
    if request.method=='POST':
        #notas=request.POST.get('nota')
        #criterios=request.POST.get('criterio')

        nota=request.POST['avaliar_revisor']
        aluno=request.user.aluno
        resposta=Resposta.objects.get(slug=slug)

        msg = resposta.posta_nota_avaliador(nota=nota,aluno=aluno)

        return redirect(reverse(viewname='aluno_comentarioEnotas',kwargs={'slug':slug}))




    return HttpResponseRedirect("/home")


#Notas idividuais de cada alunos
@login_required
@is_professor()
def getNotasAluno(request,slug_atividade):


    notas = Notas.objects.filter(resposta__atividade__slug=slug_atividade)
    data = serializers.serialize("json", notas)
    return HttpResponse(data, content_type='application/json')

avalia_pares/apps/professor/templates/alocar_trabalhos.html
{% extends 'base_professor.html' %}
{% load staticfiles %}

{% block tituloPag %}
        <h2 class="pull-left"><i class="fa fa-file-o"></i> Alocar trabalhos</h2>
{% endblock %}


{% block matter %}





		<script type="text/javascript" src="{% static 'js/jquery.dataTables.rowGrouping.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.dataTables.rowReordering.js' %}"></script>





<div class="widget-content">


                    <table class="table table-striped table-bordered table-hover" id="tb_data">
                      <thead>
                        <tr>
                          <th>Aluno</th>
                          <th>Atividade</th>
                          <th>Disciplina</th>
                          <th>Controle</th>
                        </tr>
                      </thead>

                        <tbody>


                          {% for atv in atividades %}

                        <tr>
                          <td><a class="btn btn-default" href="{% url 'Edita_Atividade' atv.slug %}">{{ atv.aluno }}</a></td>
                          <td>{{ atv.atividade.titulo }}</td>
                          <td>{{ atv.atividade.disciplina }}</td>
                          <td><a href="" class="btn btn-success"><i class=""></i> ↑</a>
                                <a href=""><button class="btn btn-danger"><i class=""></i> ↓</button></a>
                          </td>
                        </tr>
                        {% endfor %}






                      </tbody>
                    </table>



                    <button onclick="send_data()">Enviar</button>

                    </div>

                  </div>
                </div>












<script>
	$(document).ready(function(){
     $('#tb_data').dataTable().rowReordering()

});
	</script>


<script>
    function send_data() {
        $('#tb_data').dataTable( {
    "ajax": {
    "url": "http://127.0.0.1:8000/professor/alocar/teste",
    "contentType": "application/json",
    "data": function ( d ) {
      return JSON.stringify( d );
    }
  }
} );
    }

	</script>
{% endblock %}

avalia_pares/apps/professor/templates/atividades.html
{% extends 'base.html' %}
{% load tag_user %}
{% load tag_relacao_aluno_disciplina tag_relacao_disciplina %}
{% block tituloPag %}
        <h2 class="pull-left"><i class="fa fa-list-alt"></i> Disciplinas</h2>
{% endblock %}


{% block matter %}

<div class="widget-content">

<table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
    <th>Nome</th>
    <th>Professor</th>
    {% if user|active == 1 %}<th>Situação</th>{% endif %}
    {% if user|active == 2 %}<th>Controle</th>{% endif %}
    </tr>
    </thead>

<tbody>
    {% for disc in disciplinas %}
    <tr>

    {% if user|active == 1 %}
        <td><a class="btn btn-default" href="{% url 'detalhe_disciplinas' disc.slug %}">{{ disc.nome }}</a></td>
        <td>{{ disc.professor }}</td>
        <td>{{user|rel_aluno_disc:disc.id}}</td>
    {% endif %}

    {% if user|active == 2 and user|rel_prof_disc:disc.slug %}
        <td><a class="btn btn-default" href="{% url 'detalhe_disciplinas' disc.slug %}">{{ disc.nome }}</a></td>
        <td>{{ disc.professor }}</td>
        <td><a href="{% url 'Edita_Atividade' %}" class="btn btn-warning"><i class="fa fa-pencil"></i>Editar</a>
        <button class="btn btn-xs btn-danger"><i class="fa fa-times"></i>  Excluir</button></td>
    {% endif %}

    </tr>
    {% endfor %}


</tbody>
                    </table>
            
                    <div class="widget-foot">
                        {% if user|active == 2 %}
                            <a href="{% url 'professor_cria_disciplina' %}" class="btn btn-success"><i class="fa fa-plus"></i>Cadastrar Disciplina</a>
                        {% endif %}


                        <ul class="pagination pagination-sm pull-right">

                          <li><a href="#">Anterior</a></li>
                          <li><a href="#">1</a></li>
                          <li><a href="#">2</a></li>
                          <li><a href="#">3</a></li>
                          <li><a href="#">4</a></li>
                          <li><a href="#">Próxima</a></li>
                        </ul>

                      <div class="clearfix"></div>

                    </div>

                  </div>
                </div>

{% endblock %}

avalia_pares/apps/professor/templates/base_professor.html
{% extends 'base.html' %}


{% block barrasup %}
<div class="navbar navbar-fixed-top bs-docs-nav" role="banner">

            <!-- Menu button for smallar screens -->
       <ul class="nav navbar-nav pull-right">
          <li class="dropdown pull-right">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-user"></i>
                  {{ user.professor }}
                  <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                  <li><a href="{% url 'atualiza_dados_professor' %}"><i class="fa fa-user"></i>Perfil</a></li>
                  <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out"></i>Sair</a></li>
              </ul>
          </li>
       </ul>
    </div>

    <div class="content">

        <!-- Sidebar -->
        <div class="sidebar">
            <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
            <ul id="nav">
              <li><a href="{% url 'home' %}"><i class="fa fa-home"></i> Início</a></li>
              <li class="has_sub"><a href="{% url 'professor_disciplinas' %}"><i class="fa fa-list-alt"></i> Disciplinas  <span class="pull-right"></i></span></a></li>
              <li><a href="{% url 'Lista_Atividades' %}"><i class="fa fa-tasks"></i> Atividades</a></li>
              <li><a href="{% url 'atualiza_dados_professor' %}"><i class="fa fa-magic"></i> Atualizar Perfil</a></li>
            </ul>
        </div>
{% endblock %}

avalia_pares/apps/professor/templates/confirmacaoDisc.html
{% extends 'base.html' %}

{% block tituloPag %}
    <h2 class="pull-left"><i class="fa fa-list-alt"></i> Disciplina "{{nome}}" cadastrada com sucesso!</h2>

{% endblock %}

{% block matter %}

<form method="post">
    <a href="{% url 'professor_cria_disciplina' %}" class="btn btn-success"><i class="fa fa-plus"></i>   Cadastrar outra disciplina</a>
    <a href="{% url 'disciplinas' %}" class="btn btn-danger">Voltar</a>
</form>

{% endblock %}

avalia_pares/apps/professor/templates/editar_atividade.html
{% extends 'base_professor.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block tituloPag %}
    <h2 class="pull-left"><i class="fa fa-list-alt"></i> Editar Atividade</h2>
{% endblock %}

{% block matter %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/moment.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'js/fileinput.js' %}"></script>
    <script src="{% static 'js/fileinput_locale_pt-BR.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/fileinput.min.css' %}">

    <div class="container">
    <div class="row">
        <div class="col-sm-6">
    <form enctype="multipart/form-data" role="form" method="post" action="">
        {% csrf_token %}


        <div class="row1">
            <a class="btn btn-warning" target="_blank" href="{% url 'baixa_atividade' form.slug.value %}">
            <span class="btn btn-primary">

<label class="control-label">Arquivo Atual: </label >
                <div class="col-md-12">



                        <object data="{% url 'baixa_atividade' form.slug.value %}" type="application/pdf" width="160px" height="160px" internalinstanceid="45">
       <param name="movie" value="{{ form.arquivo.name }}">
      <param name="controller" value="true">
      <param name="allowFullScreen" value="true">
      <param name="allowScriptAccess" value="always">
      <param name="autoPlay" value="false">
      <param name="autoStart" value="false">
      <param name="quality" value="high">
         <div class="file-preview-other">
       <i class="glyphicon glyphicon-file"></i>
         </div>
    </object>

                </div>



            </span>
            </a>

        </div>
        {% bootstrap_form form %}

        <td><a><button class="btn btn-success" type="submit" id="enviar"> Enviar</button></a></td>
        <td><a href="{% url 'Lista_Atividades' %}" class="btn btn-danger"> Cancelar</a></td>
        <td><a class="btn btn-default" onclick="atualizaData()">Atualizar</a></td>
        <script type="text/javascript">
            $(function (){

                $('input[type=datetime]').each(function(){
                    $(this).datetimepicker({
                        format:'DD/MM/YYYY hh:mm:ss'
                    });
                });

            });

            $("#id_arquivo").fileinput({
            language: "pt-BR",
            uploadUrl: "",

            allowedFileExtensions: ["pdf"]
        });

        </script>
    </form>
    </div>
    </div>
    </div>


    <script type="text/javascript" src="{% static 'js/myjs/mydata.js' %}"></script>

{% endblock %}

avalia_pares/apps/professor/templates/excluir_atividade.html
{% extends 'base.html' %}

{% block tituloPag %}
        <h2 class="pull-left"><i class="fa fa-times"></i> Excluir {{ atividade.nome }} ?</h2>
{% endblock %}


{% block matter %}
    <form method="post">
        {% csrf_token %}
        <p>Você tem certeza que quer remover a atividade: {{ atividade }} ?</p>
        <input type="submit" value="Confirmar" class="btn btn-success">
        <a href="{% url 'Lista_Atividades' %}" class="btn btn-danger">Cancelar</a>
    </form>
{% endblock %}